### ISSUE TITLE
Create Edit document route, screen and component

### ISSUE THREAD

**Issue by davideastmond** [chingu-voyages/v50-tier3-team-24#57]
**__Task Description__**
Create the front-end route. And a document-view component.

- [x] - Create the route `/[username]/[doc-title]?edit`(this task is completed in #56)
- [x] - The correct document is fetched from the DB
- [x] - The relevant attributes of the document are displayed
- [x] - The document text/data is displayed (annotations not included for now)
- [x] - User should be able to edit the title and body and submit it as a PATCH to the backend

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by davideastmond** [comment]
Might duplicate a portion of #52
