### ISSUE TITLE
Create New Document route, screen and component

### ISSUE THREAD

**Issue by davideastmond** [chingu-voyages/v50-tier3-team-24#58]
**__Task Description__**
Create the route, screen and component that allows user to submit a document body and document title text.

- [ ] - Create the route `/library/new`
- [ ] - Allow the user to input a title for the document
- [ ] - Allow user to input body text for the document
- [ ] - Create a button that will submit a HTTP request to the backend that will save the document and title to the database

- What happens after the user successfully submits a document?

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by davideastmond** [comment]
Might duplicate a portion of #52
